### PR TITLE
Features/profile

### PR DESCRIPTION
**Pull request by natgate**

### CODE REVIEW

**Review by paul-ndl — CHANGES_REQUESTED** [review]
You have to merge with master. You have conflict files!

**Review by jules20022000 — CHANGES_REQUESTED** [review]
Clean documented code but pull the master as Paul said and then we could accept the PR

**Comment by natgate** [comment]
I already pull and merge the master

**Review by jules20022000 — APPROVED** [review]
Clean code and nice display of the user profile. Good job

**Comment by natgate** [comment]
Thanks!

**Pull request merged**
